sprites.onOverlap(SpriteKind.Guard, SpriteKind.Enemy, function (sprite, otherSprite) {
    info.changeScoreBy(1)
    Namor.setPosition(148, 100)
})
info.onScore(10, function () {
    Namor.destroy()
    scene.setBackgroundImage(assets.image`boston-bridge`)
    effects.confetti.startScreenEffect()
    game.showLongText("We are Safe!", DialogLayout.Bottom)
    Shuri.sayText("WAKANDA FOREVER", 5000, false)
    game.showLongText("We are Safe!", DialogLayout.Bottom)
    game.over(true)
})
sprites.onOverlap(SpriteKind.Player, SpriteKind.Enemy, function (sprite, otherSprite) {
    info.changeLifeBy(-1)
    sprite.setPosition(148, 100)
})
let Namor: Sprite = null
let Shuri: Sprite = null
game.showLongText("Help Shuri, Okoye and Riri escape Namor. (Press A button to go to the next screen)", DialogLayout.Full)
game.showLongText("When the game begins, press the ARROW KEYS to move Shuri, Okoye and Ruri. If Namor catches you, you will lose points!", DialogLayout.Full)
game.showLongText("Earn 10 points to win and to stay alive you must keep your heart(s).", DialogLayout.Full)
info.setLife(2)
scene.setBackgroundImage(assets.image`wakanda`)
Shuri = sprites.create(assets.image`shuri`, SpriteKind.Player)
controller.moveSprite(Shuri, 100, 100)
Shuri.setStayInScreen(true)
Namor = sprites.create(assets.image`namor`, SpriteKind.Enemy)
Shuri.setPosition(9, 100)
Namor.setPosition(148, 100)
Namor.follow(Shuri, 30)
let Riri = sprites.create(assets.image`riri`, SpriteKind.Guard)
let Okoye = sprites.create(assets.image`okoye`, SpriteKind.Guard)
controller.moveSprite(Riri, 34, -53)
controller.moveSprite(Okoye, -68, -58)
